# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d45e8543b3ef6e491b82766f3d1072cea590d0b9984023b93454baf7198451ac95f322681481c3cbedf3054cd289a4cbc591297715782080031029c62d8d0bd7

test:
  secret_key_base: 3f11954edcd11160c71a5345c8d00f320a32e28dc082e726a8b02a77fb81fe67c76139e3f3fd4d2758b11b4332ddbed8d49e26a0bca6131ff9f71d98a79b0c96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
